### ISSUE TITLE
Improve conf file for the case that checkpoint mode is disabled

### ISSUE THREAD

**Issue by ghost** [intelie/pycollector#16]
1) Currently, checkpoint mode is disabled by commenting the checkpoint-related lines in the conf file. I suggest to create an option to enable/disable the checkpoint mode.

2) Also, when pycollector runs without the checkpoint mode, the following error appears on stdout:
      "Error writing checkpoint in None coercing to Unicode: need string or buffer, NoneType found"

**Comment by cathoderay** [comment]
1) good point, gonna fix
2) already fixed, ;)

**Comment by cathoderay** [comment]
1) Implemented. 
Now you can add a 'checkpoint_enabled' attribute in conf.yaml
'checkpoint_enabled: True' will deal with checkpoints
'checkpoint_enabled: False' will disable checkpoints
